# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48e1164c04eb2f5d67468a41569b276419ca179a404c0647ede00495b51b5ddf56c703a1e13d406a92601ecf95f32935fe8f506ed5de78373642db0785e6b51e

test:
  secret_key_base: 22ad5641dc323c4c366955fbddba01b8e8487eeed7ca47bd1f03976ba66c6175532a6e3975cefd7b44fde8b2687ddc86960e15bb702a3d5ad59942eb26e92ed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
